version: "3"
services:
  app:
    env_file:
      - .development.env
    container_name: AMS-backend
    restart: always
    build: .
    ports:
      - 3000:3000
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: AMS-backend
        POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - postgres
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
